// <auto-generated />
using MasteryTrackedDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MasteryTrackedDB.Migrations
{
    [DbContext(typeof(SkillMasteryContext))]
    partial class SkillMasteryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MasteryTrackedDB.SkillToMaster", b =>
                {
                    b.Property<int>("SkillToMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrYrHrs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstYrsToMast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PercToMast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubSkillID")
                        .HasColumnType("int");

                    b.Property<string>("SubSkillList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotSkillHrs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsersID")
                        .HasColumnType("int");

                    b.HasKey("SkillToMasterId");

                    b.HasIndex("SubSkillID");

                    b.HasIndex("UsersID");

                    b.ToTable("SkillToMasters");
                });

            modelBuilder.Entity("MasteryTrackedDB.SubSkill", b =>
                {
                    b.Property<int>("SubSkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.Property<string>("SubSkillList")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubSkillID");

                    b.ToTable("SubSkill");
                });

            modelBuilder.Entity("MasteryTrackedDB.Users", b =>
                {
                    b.Property<int>("UsersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsersID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MasteryTrackedDB.SkillToMaster", b =>
                {
                    b.HasOne("MasteryTrackedDB.SubSkill", "subSkill")
                        .WithMany("skillToMasters")
                        .HasForeignKey("SubSkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasteryTrackedDB.Users", "user")
                        .WithMany("SkillToMaster")
                        .HasForeignKey("UsersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("subSkill");

                    b.Navigation("user");
                });

            modelBuilder.Entity("MasteryTrackedDB.SubSkill", b =>
                {
                    b.Navigation("skillToMasters");
                });

            modelBuilder.Entity("MasteryTrackedDB.Users", b =>
                {
                    b.Navigation("SkillToMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
